### ISSUE TITLE
Exception on how-to from the readme

### ISSUE THREAD

**Issue by pviotti** [wgolab/WatCA#1]
Hello,

I got this NullPointerException trying the how-to from the readme file:

![image](https://cloud.githubusercontent.com/assets/1350095/22508505/9481bc9a-e88a-11e6-94d5-489f473302be.png)

Probably that shell file just needs to be updated.

Otherwise, interesting project! (Actually I made [something similar](https://github.com/pviotti/conver-scala), recently).
Cheers!

**Comment by wgolab** [comment]
Thanks for pointing this out.  A bug fix is underway.

**Comment by wgolab** [comment]
The parser was incorrectly dropping log lines for read responses that return the empty string.  This issue is now fixed.
