### ISSUE TITLE
Mistakenly report the inconsistency

### ISSUE THREAD

**Issue by likai1993** [wgolab/WatCA#3]
Hi there,

First I want to express gratitude to your great work and sharing your open source code.

I have tried to test your work in detecting the inconsistency against some operation trace, while I found that your open source program mistakenly reports the inconsistency, indeed it is a consistent log.  Below are the operation trace that your program reports mistakenly:
'''
1556833007613435147	INV	01	W	user12161962213042174405 field0=bbbbbbbbbb 	
1556833007614526914	RES	01	W	user12161962213042174405
1556833025229800457	INV	01	W	user12161962213042174405	field0=vvvvvvvvvv 	
1556833025230878397	RES	01	W	user12161962213042174405
1556833025231061954	INV	01	W	user12161962213042174405	field0=%%%%%%%%%% 	
1556833025232126091	RES	01	W	user12161962213042174405
1556833025232152622	INV	01	W	user12161962213042174405	field0=bbbbbbbbbb 	
1556833025233242958	RES	01	W	user12161962213042174405
'''

Running your program will get the following output:
'''
Running
Scores calculated successfully!  Open up lintest_output and see for yourself.
Done
Score 0: 0 occurrences
Score 1: 2 occurrences
Score 2: 0 occurrences
Explanation: 
0 means OK
1 means linearizability violation (bug!)
2 means a get operation returned a value that was never assigned by a put operation (bug!)
'''

As you can see, the above trace consists of write-only operations and there should be no inconsistency in terms of write-only operations, may I know where the problem could be?

**Comment by wgolab** [comment]
Your trace contains two write operations that assign the same value (field0=bbbbbbbbbb) to the same key.  This breaks one of the assumptions underlying the analyzer.  I pushed in an update that reports a Score 3 in this case, which indicates a bad input.  Please let us know if this solves your problem.
